export const UPDATE_PATIENT_ID = 'UPDATE_PATIENT_ID';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_CURRENT_PATIENT = 'UPDATE_CURRENT_PATIENT';
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';
export const DUMMY_TYPE = 'DUMMY_TYPE';
